### PR TITLE
Use &[u8] instead of &Vec<u8>

### PR DESCRIPTION
**Pull request by panicbit**

### CODE REVIEW

**Comment by tarcieri** [comment]
Thanks for the PR. This covers some but not all of the cases. Also the format is about to change. But since `master` is in a state of flux anyway, I'll call this an improvement.

**Comment by panicbit** [comment]
Not sure what you mean exactly. Did I miss some &Vec<T> somewhere?

**Comment by tarcieri** [comment]
Yes, there are several fields still using `Vec<u8>`, like `identifier` and `location`

**Comment by panicbit** [comment]
No, those are fine. You'll want to consume the identifier and probably also the location.

**Comment by tarcieri** [comment]
So playing the devil's advocate: why can't they be immutably borrowed as a `&[u8]`? (and use e.g. `std::borrow::Cow`)

**Comment by panicbit** [comment]
`&[u8]` would be bad because it would either force you to
a) clone the data, even if the caller doesn't need the original data anymore (unnecessary clone) or
b) add a lifetime parameter to `Token` (reduced usability)

`Cow` would allow you to pass either an owned or a borrowed value, but using `ToOwned` or `Into` instead would probably be much more ergonomic (the caller wouldn't need to explicitly clone anymore).

**Pull request merged**
